// <auto-generated />
namespace MvcHtmlHelpers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_Employee_Moblie_Validation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_Employee_Moblie_Validation));
        
        string IMigrationMetadata.Id
        {
            get { return "202012251843009_update_Employee_Moblie_Validation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
